/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadImageRouteImport } from './routes/api/download-image'

const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadImageRoute = ApiDownloadImageRouteImport.update({
  id: '/api/download-image',
  path: '/api/download-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disclaimer' | '/inspiration' | '/api/download-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disclaimer' | '/inspiration' | '/api/download-image'
  id: '__root__' | '/' | '/disclaimer' | '/inspiration' | '/api/download-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InspirationRoute: typeof InspirationRoute
  ApiDownloadImageRoute: typeof ApiDownloadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-image': {
      id: '/api/download-image'
      path: '/api/download-image'
      fullPath: '/api/download-image'
      preLoaderRoute: typeof ApiDownloadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  InspirationRoute: InspirationRoute,
  ApiDownloadImageRoute: ApiDownloadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
