/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDownloadImageRouteImport } from './routes/api/download-image'
import { Route as ApiUploadsInputImageRouteImport } from './routes/api/uploads/input-image'
import { Route as ApiUploadsAvatarRouteImport } from './routes/api/uploads/avatar'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiAuthRequestPasswordResetRouteImport } from './routes/api/auth/request-password-reset'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminVerifyAccessPasswordRouteImport } from './routes/api/admin/verify-access-password'
import { Route as ApiAdminProviderTaskDiagnosticRouteImport } from './routes/api/admin/provider-task-diagnostic'

const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadImageRoute = ApiDownloadImageRouteImport.update({
  id: '/api/download-image',
  path: '/api/download-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsInputImageRoute = ApiUploadsInputImageRouteImport.update({
  id: '/api/uploads/input-image',
  path: '/api/uploads/input-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsAvatarRoute = ApiUploadsAvatarRouteImport.update({
  id: '/api/uploads/avatar',
  path: '/api/uploads/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestPasswordResetRoute =
  ApiAuthRequestPasswordResetRouteImport.update({
    id: '/api/auth/request-password-reset',
    path: '/api/auth/request-password-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyAccessPasswordRoute =
  ApiAdminVerifyAccessPasswordRouteImport.update({
    id: '/api/admin/verify-access-password',
    path: '/api/admin/verify-access-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminProviderTaskDiagnosticRoute =
  ApiAdminProviderTaskDiagnosticRouteImport.update({
    id: '/api/admin/provider-task-diagnostic',
    path: '/api/admin/provider-task-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/api/admin/provider-task-diagnostic': typeof ApiAdminProviderTaskDiagnosticRoute
  '/api/admin/verify-access-password': typeof ApiAdminVerifyAccessPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/input-image': typeof ApiUploadsInputImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/api/admin/provider-task-diagnostic': typeof ApiAdminProviderTaskDiagnosticRoute
  '/api/admin/verify-access-password': typeof ApiAdminVerifyAccessPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/input-image': typeof ApiUploadsInputImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/api/download-image': typeof ApiDownloadImageRoute
  '/api/admin/provider-task-diagnostic': typeof ApiAdminProviderTaskDiagnosticRoute
  '/api/admin/verify-access-password': typeof ApiAdminVerifyAccessPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/auth/request-password-reset': typeof ApiAuthRequestPasswordResetRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/uploads/avatar': typeof ApiUploadsAvatarRoute
  '/api/uploads/input-image': typeof ApiUploadsInputImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/api/admin/provider-task-diagnostic'
    | '/api/admin/verify-access-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-password-reset'
    | '/api/public/contact'
    | '/api/uploads/avatar'
    | '/api/uploads/input-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/api/admin/provider-task-diagnostic'
    | '/api/admin/verify-access-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-password-reset'
    | '/api/public/contact'
    | '/api/uploads/avatar'
    | '/api/uploads/input-image'
  id:
    | '__root__'
    | '/'
    | '/disclaimer'
    | '/inspiration'
    | '/api/download-image'
    | '/api/admin/provider-task-diagnostic'
    | '/api/admin/verify-access-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/auth/request-password-reset'
    | '/api/public/contact'
    | '/api/uploads/avatar'
    | '/api/uploads/input-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InspirationRoute: typeof InspirationRoute
  ApiDownloadImageRoute: typeof ApiDownloadImageRoute
  ApiAdminProviderTaskDiagnosticRoute: typeof ApiAdminProviderTaskDiagnosticRoute
  ApiAdminVerifyAccessPasswordRoute: typeof ApiAdminVerifyAccessPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiAuthRequestPasswordResetRoute: typeof ApiAuthRequestPasswordResetRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiUploadsAvatarRoute: typeof ApiUploadsAvatarRoute
  ApiUploadsInputImageRoute: typeof ApiUploadsInputImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-image': {
      id: '/api/download-image'
      path: '/api/download-image'
      fullPath: '/api/download-image'
      preLoaderRoute: typeof ApiDownloadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/input-image': {
      id: '/api/uploads/input-image'
      path: '/api/uploads/input-image'
      fullPath: '/api/uploads/input-image'
      preLoaderRoute: typeof ApiUploadsInputImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/avatar': {
      id: '/api/uploads/avatar'
      path: '/api/uploads/avatar'
      fullPath: '/api/uploads/avatar'
      preLoaderRoute: typeof ApiUploadsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request-password-reset': {
      id: '/api/auth/request-password-reset'
      path: '/api/auth/request-password-reset'
      fullPath: '/api/auth/request-password-reset'
      preLoaderRoute: typeof ApiAuthRequestPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify-access-password': {
      id: '/api/admin/verify-access-password'
      path: '/api/admin/verify-access-password'
      fullPath: '/api/admin/verify-access-password'
      preLoaderRoute: typeof ApiAdminVerifyAccessPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/provider-task-diagnostic': {
      id: '/api/admin/provider-task-diagnostic'
      path: '/api/admin/provider-task-diagnostic'
      fullPath: '/api/admin/provider-task-diagnostic'
      preLoaderRoute: typeof ApiAdminProviderTaskDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisclaimerRoute: DisclaimerRoute,
  InspirationRoute: InspirationRoute,
  ApiDownloadImageRoute: ApiDownloadImageRoute,
  ApiAdminProviderTaskDiagnosticRoute: ApiAdminProviderTaskDiagnosticRoute,
  ApiAdminVerifyAccessPasswordRoute: ApiAdminVerifyAccessPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiAuthRequestPasswordResetRoute: ApiAuthRequestPasswordResetRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiUploadsAvatarRoute: ApiUploadsAvatarRoute,
  ApiUploadsInputImageRoute: ApiUploadsInputImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
